---
- name: Set the placement key
  when:
  - l_item.key is search("placement." + appGroupingKeySuffix)
  set_fact:
    placementKey: "{{ l_item.value }}"
  loop: "{{ c_item.value | dict2items }}"
  loop_control:
    label: "{{ l_item.key }}"
    loop_var: l_item

- name: dump placementKey
  debug:
    msg: "{{ placementKey }}"