
- name: Loop through the clusters and their labels
  when:
  - l_item.key is search(appGroupingKeySuffix)
  - l_item.value == "deploy"
  set_fact:
    matchedClusters: "{{ matchedClusters | combine( { l_item.key: l_item.value } ) }}"
  loop: "{{ c_item.value | dict2items }}"
  loop_control:
    label: "{{ l_item.key }}"
    loop_var: l_item