---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mario-appset
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  mario.apps.acme.org: deploy
                  placement.mario.apps.acme.org: active
          - list:
              elements:
              - appName: mario
                namespace: mario
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - repoURL: https://github.com/kenmoini/acm-eda-dr
          path: apps/mario
          targetRevision: main
          kustomize: {}
      destination:
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5