---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: local-cluster
  namespace: open-cluster-management-policies
placementRef:
  name: local-cluster
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: health-mc-addons
    apiGroup: policy.open-cluster-management.io
    kind: Policy