---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-clusters
  namespace: open-cluster-management-policies
placementRef:
  name: openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: health-clusteroperator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: health-clusterversion
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: health-machineconfigpool
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: health-node
    apiGroup: policy.open-cluster-management.io
    kind: Policy