---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-clusters
  namespace: open-cluster-management-policies
placementRef:
  name: openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: mc-clusteroperator-health
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: mc-clusterversion-health
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: mc-machineconfigpool-health
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: mc-node-health
    apiGroup: policy.open-cluster-management.io
    kind: Policy