# This ansible playbook is triggered via EDA from Alertmanager alerts.
# This decides what to do based on what sort of Policy violation was detected.
---
- name: Decision - Policy Violation
  hosts: all
  vars:
    appGroupingKeySuffix: apps.acme.org
    appClusterTargetKeyPrefix: target
    appPlacementKeyPrefix: placement

  tasks:

  - name: Dump all vars
    debug:
      var: vars

  - name: Run functions for a downed cluster - Failing Inform
    when:
      - ansible_eda.event.alert.labels.policy in ['open-cluster-management-policies.failing-inform']
    block:
      - name: YEP
        debug:
          msg: "This is a Failing Inform policy violation - this is meant to be a test unless the 'i-do-not-exist' namespace is created on a cluster"

  - name: Run functions for a downed cluster - App DR
    when:
      - ansible_eda.event.alert.labels.policy in ['open-cluster-management-policies.health-mc-addons']
    block:
      - name: Process Application DR
        ansible.builtin.include_tasks: toggleAppDR.yaml