name: EE build and push - Process Policy Violation

on:
  pull_request:
    paths:
      - 'rulebooks/process-policy-violation/**'
  push:
    branches:
      - main
    paths:
      - 'rulebooks/process-policy-violation/**'
      - '.github/workflows/build-process-policy-violation-ee.yml'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses: kenmoini/disconnected-openshift/.github/workflows/base-build-ee.yml@main
    #uses: kenmoini/ansible-ee-builder/.github/workflows/build-ee-base.yml@main
    with:
      #ENABLE_REDHAT_REGISTRY: true
      REGISTRY_HOSTNAME: quay.io
      REGISTRY_PATH: kenmoini
      EE_IMAGE_NAME: 'ee-process-policy-violation'
      EE_IMAGE_TAG: 'latest'
      EE_FOLDER_NAME: 'rulebooks/process-policy-violation'
      EE_FILE_NAME: execution-environment.yml
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
      #REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      #REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}